try {
  throw new Error('caught!');
} catch (err) {
  console.error(err);
};
